import "./globals.css";
import { Geist } from "next/font/google";
import { QueryProviders } from "@/features/shared/query-providers";
import { Navbar } from "@/features/shared/navbar";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased dark`}
      >
        <Navbar />
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
}
