/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query PopularAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: POPULARITY_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": typeof types.PopularAnimeDocument,
    "\n  query SeasonalAnime($season: MediaSeason, $seasonYear: Int, $page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(\n        type: ANIME\n        season: $season\n        seasonYear: $seasonYear\n        sort: POPULARITY_DESC\n      ) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": typeof types.SeasonalAnimeDocument,
    "\n  query TopRatedAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: SCORE_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": typeof types.TopRatedAnimeDocument,
    "\n  query TrendingAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: TRENDING_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": typeof types.TrendingAnimeDocument,
};
const documents: Documents = {
    "\n  query PopularAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: POPULARITY_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": types.PopularAnimeDocument,
    "\n  query SeasonalAnime($season: MediaSeason, $seasonYear: Int, $page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(\n        type: ANIME\n        season: $season\n        seasonYear: $seasonYear\n        sort: POPULARITY_DESC\n      ) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": types.SeasonalAnimeDocument,
    "\n  query TopRatedAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: SCORE_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": types.TopRatedAnimeDocument,
    "\n  query TrendingAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: TRENDING_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n": types.TrendingAnimeDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PopularAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: POPULARITY_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').PopularAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SeasonalAnime($season: MediaSeason, $seasonYear: Int, $page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(\n        type: ANIME\n        season: $season\n        seasonYear: $seasonYear\n        sort: POPULARITY_DESC\n      ) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').SeasonalAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TopRatedAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: SCORE_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').TopRatedAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TrendingAnime($page: Int, $perPage: Int) {\n    Page(page: $page, perPage: $perPage) {\n      pageInfo {\n        total\n        currentPage\n        lastPage\n        hasNextPage\n        perPage\n      }\n      media(type: ANIME, sort: TRENDING_DESC) {\n        id\n        title {\n          romaji\n          english\n          native\n          userPreferred\n        }\n        description\n        coverImage {\n          large\n          medium\n          extraLarge\n          color\n        }\n        bannerImage\n        averageScore\n        meanScore\n        popularity\n        favourites\n        status\n        genres\n        tags {\n          id\n          name\n          description\n          category\n          rank\n        }\n        format\n        duration\n        episodes\n        startDate {\n          year\n          month\n          day\n        }\n        endDate {\n          year\n          month\n          day\n        }\n        season\n        seasonYear\n        countryOfOrigin\n        source\n        hashtag\n        synonyms\n        siteUrl\n        isAdult\n        nextAiringEpisode {\n          airingAt\n          timeUntilAiring\n          episode\n        }\n        trending\n        studios(isMain: true) {\n          nodes {\n            id\n            name\n            siteUrl\n            isAnimationStudio\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').TrendingAnimeDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
